### ISSUE TITLE
Add read the docs configuration file

### ISSUE THREAD

**Issue by mfaafm** [ionelmc/cookiecutter-pylibrary#176]
Hi, 
there is a new way to specify configuration of read the docs build using their ``.readthedocs.yml`` configuration files. The advantages are:

- The build environment can be configured in the repo
- The user does not have to change the advanced settings in the UI, since the ``.readthedocs.yml`` overrides the UI settings. 

I suggest to add it to the cookiecutter template.
If I see it correctly there are no settings in the template to change the docs location or similar, so a very simple configuration file shouls suffice.

This is the ``.readthedocs.yml`` I use in my project, which used your cookiecutter:
```yaml
# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2

sphinx:
  configuration: docs/conf.py

formats: all

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
```
