### ISSUE TITLE
Simplify AppVeyor build matrix

### ISSUE THREAD

**Issue by vmuriart** [ionelmc/cookiecutter-pylibrary#76]
AppVeyor lets you combine `configuration`, `platform` and `matrix` and builds each combination of the three variables on the [yml config](https://www.appveyor.com/docs/build-configuration/#build-matrix)

We used this to greatly simplify [our AppVeyor config](https://github.com/pythonnet/pythonnet/commit/a356dcc7740b28dbe631b6fdb11bdc83384298f6#diff-180360612c6b8c4ed830919bbb4dd459). Our current version is a bit [leaner](https://github.com/pythonnet/pythonnet/blob/6095de8c997661a29c9e8ac60ab5605a3639e83f/appveyor.yml#L22-L28) too.

For example, the setup below build on `2.7`-`3.6` on both `x86` and `x64`. All other related environment variables are computed and set during `init`.

```yaml
platform:
  - x86
  - x64

environment:
  matrix:
    - PYTHON_VERSION: 2.7
    - PYTHON_VERSION: 3.3
    - PYTHON_VERSION: 3.4
    - PYTHON_VERSION: 3.5
    - PYTHON_VERSION: 3.6

init:
  # Update Environment Variables based on matrix/platform
  - set PY_VER=%PYTHON_VERSION:.=%
  - set PYTHON=C:\PYTHON%PY_VER%
  - if %PLATFORM%==x64 (set PYTHON=%PYTHON%-x64)

  # Put desired Python version first in PATH
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

install:
  - pip install --upgrade -r requirements.txt --quiet
```

There are many ways to integrate this into your `cookiecutter` template, so I opened a ticket to see if its something worth integrating to it.

**Comment by vmuriart** [comment]
Here's [another](https://bitbucket.org/hyllos/effectus-python/diff/appveyor.yml?diff2=fdb81dae7f95&at=default) project that switched over recently.

**Comment by ionelmc** [comment]
In case I'm missing it, your examples don't do any of these right?

* install python if not installed 
* support tox

This is why cookiecutter-pylibrary's config looks so heavy (TOXPYTHON is to set the unexpected python exe path, and the extra PYTHON_ARCH/PYTHON_VERSION env vars are for the [install script](https://github.com/ionelmc/python-nameless/blob/master/ci/appveyor-bootstrap.py)).

Also note that the matrix it's not something that you'd write and maintain by hand, there's a template: https://github.com/ionelmc/python-nameless/blob/master/ci/templates/appveyor.yml

Still think it could be simpler while supporting those two usecases?

**Comment by ionelmc** [comment]
I notice that https://bitbucket.org/hyllos/effectus-python/diff/appveyor.yml?diff2=fdb81dae7f95&at=default was quite similar to the matrix in pylibrary, tho it doesn't seem to have the python install script anymore.

Maybe we could use the `platforms` list, tho the `matrix` would still have to look like this (to support the `<pythonverstion>-<djangoversion>` sort of tox environments ):

```yaml
matrix:
- TOXENV: 3.3
- PYTHON_VERSION: 3.3
- TOXENV: 3.4
- PYTHON_VERSION: 3.4
- TOXENV: 3.5
- PYTHON_VERSION: 3.5
```

**Comment by vmuriart** [comment]
We used to install `conda` and used the same variables as you did, the [example](https://github.com/pythonnet/pythonnet/commit/a356dcc7740b28dbe631b6fdb11bdc83384298f6#diff-180360612c6b8c4ed830919bbb4dd459) actually still installed conda and created the appropriate environment we needed. 

In my project, we couldn't use `tox` on our CI enviroment because of the nature of the project. The [2nd project](https://bitbucket.org/hyllos/effectus-python/diff/appveyor.yml?diff2=fdb81dae7f95&at=default) I listed though had no issues with it. I suspect he based his initial config off Pylibrary.

It would simplify the template, but it really depends on the use case. If anything it would atleast shorten up having to specify both 32/64 bit matrices .

**Comment by vmuriart** [comment]
did you mean

```yaml
matrix:
- TOXENV: 3.3
  PYTHON_VERSION: 3.3
- TOXENV: 3.4
  PYTHON_VERSION: 3.4
- TOXENV: 3.5
  PYTHON_VERSION: 3.5
```

if so, you could use

```yaml
matrix:
- PYTHON_VERSION: 3.3
- PYTHON_VERSION: 3.4
- PYTHON_VERSION: 3.5

init:
  # Update Environment Variables based on matrix/platform
  - set TOXENV=%PYTHON_VERSION%
```

**Comment by janLuke** [comment]
@ionelmc It seems that AppVeyor plays well with tox now: https://www.appveyor.com/docs/lang/python/
```yml
---
environment:
  matrix:
  - TOXENV: py27
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: py37

build: off

install:
- pip install tox

test_script:
- tox
```
